/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    JpsBtn: typeof import('./../JPSBtn/JpsBtn.vue')['default']
    JpsCard: typeof import('./../JPSCard/JpsCard.vue')['default']
  }
}
